site_name: GitHub Meister Documentation
repo_url: https://github.com/robvanderleek/ghmeister
theme:
  name: material
  palette:
  - scheme: default
    primary: black
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - toc.integrate
    - navigation.footer
    - content.code.copy
plugins:
  - termynal
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
markdown_extensions:
  - attr_list
nav:
  - 'index.md'
