name: "Release"

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: GitHub token
        required: true
      NPM_TOKEN:
        description: NPM token
        required: true

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: "Force HTTPS"
        run: git config --global url."https://github".insteadOf ssh://git@github

      - name: "Install dependencies"
        run: yarn install

      - name: "Compile TypeScript"
        run: yarn build

      - name: "Semantic Release"
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
