name: "Build and run tests"

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
      env:
        CI: true
      steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4

      - name: 'Setup NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 'Force HTTPS'
        run: git config --global url."https://github".insteadOf ssh://git@github

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Run tests'
        run: yarn test